### ISSUE TITLE
CPU Load issues

### ISSUE THREAD

**Issue by tomneedham** [hcodes/snowflakes#1]
Hey :) Implemented this library over at ownCloud for a nice xmas feel: https://marketplace.owncloud.com/apps/xmas but browser CPU load is a bit of an issue.

With the default settings (count: 50 and speed 1) my Chrome browser uses 75% CPU.

**Comment by hcodes** [comment]
Thanx, I will look.

**Comment by tomneedham** [comment]
Maybe we can throttle the fps? 60 max would seem appropriate, if we can give the browser some rest

**Comment by hcodes** [comment]
CSS animation will help.
PR #2

**Comment by hcodes** [comment]
Done. [v2.0.1](https://github.com/hcodes/snowflakes/releases)
