### ISSUE TITLE
turn off for mobile?

### ISSUE THREAD

**Issue by theraw** [hcodes/snowflakes#11]
Hello

First thank you for this script,

i'm using it on my site, but when i tried to visit my site from mobile it totally freezes :confused: 

Is here any way to turn snowflakes off for mobile visitors? if yes can you please give some help? i'm using this script https://unpkg.com/magic-snowflakes@3.0.0/dist/snowflakes.js

Thank you

**Comment by hcodes** [comment]
What model of phone?

**Comment by theraw** [comment]
i think will be better if i turn off for all :/

**Comment by hcodes** [comment]
```js
var isMobile = navigator.userAgent.match(/(Android|webOS|iPhone|iPad|iPod|BlackBerry|Windows Phone)/i);
if (!isMobile) {
    Snowflakes();
}
```
Links:
+ http://detectmobilebrowsers.com/
+ https://www.google.com/search?q=detect+mobile+user+agent+javascript&ie=utf-8&oe=utf-8&gws_rd=cr&dcr=0&ei=1K9EWqX0GceS6AT04IjoAw

**Comment by theraw** [comment]
Thank you alot!
