### ISSUE TITLE
[4.1.0] TypeError: Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by hartwork** [hcodes/snowflakes#19]
Hi!

I have copied this code ..
```
<script src="https://unpkg.com/magic-snowflakes/dist/snowflakes.min.js"></script>
<script>
    var sf = new Snowflakes({
        color: "#fffee8",
        rotation: false,
        minSize: 18,
        maxSize: 31
    });
</script>
```
.. from the bottom of https://hcodes.github.io/demo-snowflakes/ into the very end of `<head>...</head>`.
I get this error on the JS console in Chromium:
```
snowflakes.min.js:formatted:151 Uncaught TypeError: Cannot read property 'appendChild' of null
    at new l (snowflakes.min.js:formatted:151)
    at new <anonymous> (snowflakes.min.js:formatted:262)
    at ?next=/:25
```
That `?next=/` is from the URL where the code is served, i.e. `http://127.0.0.1:58000/login/?next=/`.

Is this a bug or do I need to make changes on my end?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
Looks like I missed the part that it needs to go into `<body>..</body>`...

**Comment by hcodes** [comment]
Fixed.

**Comment by hcodes** [comment]
https://hcodes.github.io/demo-snowflakes/index.html
https://github.com/hcodes/demo-snowflakes/commit/c5bc8e5f727668a09434128ad3a36a7c6209492b

**Comment by hartwork** [comment]
_Nice_, thank you!
