### ISSUE TITLE
Safari visual bug

### ISSUE THREAD

**Issue by BenRoe** [hcodes/snowflakes#21]
Hi,
i use you script on my shop page, but i get a visual bug (only OSX Safari) if i scroll.
Can you (@hcodes) test it? 
I have OSX 10.14.1 and Safari 12.0.1
![snowflake-safari](https://user-images.githubusercontent.com/643834/51789937-033ed480-218f-11e9-814a-2845616bbf1e.gif)

**Comment by hcodes** [comment]
Fixed.
v4.1.1.

**Comment by BenRoe** [comment]
Will test it this evening. What was the problem?

**Comment by hcodes** [comment]
Previously, the container had no height. Now added and a container with snowflakes is not shaking (only Safari) when scrolling the page.
https://github.com/hcodes/snowflakes/blob/master/src/less/main.less#L17

**Comment by hcodes** [comment]
I didn't understand. Has the problem been fixed on your website?

**Comment by BenRoe** [comment]
I tested it and it works. Many thanks for the quick fix.
