### ISSUE TITLE
Vary z-index?

### ISSUE THREAD

**Issue by strarsis** [hcodes/snowflakes#27]
I have a compositional header with different elements that have different z-indices.
Snowflakes with varying z-index would look very cool because some of them would fall behind the header elements and some in front of them, which looks 3D and realistic.

**Comment by strarsis** [comment]
Edit: I notice some variation of z-indices of the snowflakes as some go over some element, and some below. However, z-indices range option and documentation for a defined behaviour would be great, 
because this seems to be an unintended side-effect that may be removed later if this isn't a feature.

**Comment by hcodes** [comment]
https://github.com/hcodes/snowflakes/blob/master/src/js/flake.js#L41

**Comment by codenchips** [comment]
> Edit: I notice some variation of z-indices of the snowflakes as some go over some element, and some below. However, z-indices range option and documentation for a defined behaviour would be great,
> because this seems to be an unintended side-effect that may be removed later if this isn't a feature.

I was looking through the source because I couldn't get zindex to work at all. I have a canvas based video on my home page which the flakes always go behind no matter what I do.

I see this line;             
`styleProps.zIndex = params.zIndex + this.size * 10;`

Isn't that saying the zindex is set depending in the size of the flake?

**Comment by hcodes** [comment]
https://hcodes.github.io/snowflakes/examples/z-index.html

Small snowflakes are located at the far distance, they are located under large snowflakes.

**Comment by hcodes** [comment]
<img width="864" alt="изображение" src="https://user-images.githubusercontent.com/157520/100933006-c2881300-34fd-11eb-89d8-f656c2abba67.png">
z-index is set for snowflake common container.

**Comment by hcodes** [comment]
v4.2.0

**Comment by strarsis** [comment]
@hcodes: Would it be possible to have individual z-indices? I have a complex scene containing elements with different z-index, and the snowflakes should correctly visually go behind/before those elements.
