### ISSUE TITLE
Node engine minimum version for browser library

### ISSUE THREAD

**Issue by lalop** [hcodes/snowflakes#50]
Is there a reason why you added a minimum node engine version for a browser library ? Isn't that useless ?
https://github.com/hcodes/snowflakes/blob/master/package.json#L29

**Comment by hcodes** [comment]
What version do you need?

**Comment by hcodes** [comment]
Fixed.

**Comment by lalop** [comment]
hello @hcodes, thank you for the update.
Anyway, a user with node 8 can't install this library with npm since it requires node >10
But I don't understand why you specify a node requirement for a pure browser library. I may miss something.

**Comment by hcodes** [comment]
I don't want users to use old versions of Node.js. This increases the cost of package support. Only new versions of Node.js. This is a general policy for me.

**Comment by lalop** [comment]
Ok, I get it
