### ISSUE TITLE
Snow stops on my phone when I touch/scroll

### ISSUE THREAD

**Issue by honzajavorek** [hcodes/snowflakes#51]
Hi, thanks for an amazing library ❄️ I'm using it on this page https://junior.guru/gift/, the code [looks like this](https://github.com/honzajavorek/junior.guru/blob/b58d9425741275db6c1384ae5b95f30e0a82117a/juniorguru/web/static/src/js/snow.js):

```js
import Snowflakes from 'magic-snowflakes';

document.addEventListener('DOMContentLoaded', function () {
  const snow = document.getElementById('snow');
  if (snow) {
    const snowflakes = new Snowflakes({
      color: '#fff',
      container: document.getElementById('snow'),
      count: 50,
      minSize: 5,
      maxSize: 15,
      speed: 0.5
    });
    snowflakes.start();
  }
});
```

On desktop it snows correctly, but on my iPhone X, it snows only if I steadily look at the top of the page. When I scroll, the snowflakes disappear. When I stop touching the display and stop scrolling, the snow continues, or better word is probably "restarts", from the top. Do you have an idea what could be wrong?

**Comment by honzajavorek** [comment]
I wasn't able to get the same behavior in Firefox' simulator of a smaller viewport, so I think it's not the viewport size. But I can see similar behavior when I resize the window. Is it possible that the phone's browser somehow sends resize events when touching/scrolling? 🤔 Or perhaps something else on the page does it? 🤔

**Comment by honzajavorek** [comment]
So apparently it's because when scrolling, iPhone hides the address bar of the browser and that changes the size of the viewport 🤦‍♂️ Not sure what can I do about this tho.

**Comment by katemihalikova** [comment]
@honzajavorek uses snow inside a container that has variable height depending on viewport width, but that means that the height of the container does not change when only height of the viewport gets changed. In such case, resetting snow on resize is not needed. One possible solution that comes to my mind is to check in `handleResize` that the height of the container actually changed.

**Comment by mukhammad-akilov** [comment]
I also faced the same issue in Google Chrome (latest version) for Android

**Comment by hcodes** [comment]
Fixed.
Version 6.0.1.

**Comment by honzajavorek** [comment]
Awesome, thank you @hcodes! ❤️
