### ISSUE TITLE
Рандомная стартовая позиция снежинок

### ISSUE THREAD

**Issue by YAMER1** [hcodes/snowflakes#53]
Здравствуйте, сделайте, пожалуйста, так, чтобы снежинки всегда стартовали с рандомной позиции. Сейчас они падают и стартуют с той же позиции, анимация повторяется. А также хотелось бы увидеть рандомное перемещение снежинок по экрану, сейчас они качаются в разные стороны и соблюдают траекторию движения (ветер включен)

**Comment by YAMER1** [comment]
Я так понял, что теперь только через год можно ждать апдейтов?

**Comment by hcodes** [comment]
Повторяемость связана из-за CSS внимаций, этот момент можно пофиксить в ближайшее время. А вот для рандомного перемещения по экрану придётся переделать всю отрисовку на Canvas.

**Comment by YAMER1** [comment]
> Повторяемость связана из-за CSS-анимаций, этот момент можно пофиксить в ближайшее время. А вот для рандомного перемещения по экрану придётся переделать всю отрисовку на Canvas.

Хорошо, пофиксите, пожалуйста.

**Comment by YAMER1** [comment]
Здравствуйте, на зиму 2023 планируете сделать?

**Comment by hcodes** [comment]
Постараюсь, но боюсь обещать :(

**Comment by YAMER1** [comment]
Здравствуйте, скоро снег пойдёт, сделаете или опять год ждать?

**Comment by YAMER1** [comment]
Здравствуйте, снег уже идёт. Рандомную стартовую позицию стоит ждать в этом году?

**Comment by hcodes** [comment]
https://github.com/hcodes/snowflakes/pull/65

**Comment by YAMER1** [comment]
Не прошло и 10 лет, спасибо)
