### ISSUE TITLE
After the code is encrypted and compressed with Base64, it cannot be used normally

### ISSUE THREAD

**Issue by ZiXia1** [hcodes/snowflakes#54]
After the code is encrypted and compressed with Base64, it cannot be used normally

**Comment by hcodes** [comment]
Need details.
@ZiXia1

**Comment by ZiXia1** [comment]
> Need details.
> @ZiXia1 

![Screenshot_20211227-171004209.jpg](https://user-images.githubusercontent.com/66472729/147455776-d25542df-5eed-44a0-83b0-643b4e54118f.jpg)![Screenshot_20211227-171023552.jpg](https://user-images.githubusercontent.com/66472729/147455782-8b270f1a-6bf9-4ddb-9d08-44ba9f33ec41.jpg)![Screenshot_20211227-171055186.jpg](https://user-images.githubusercontent.com/66472729/147455790-cdc056bc-998e-45ba-b5e0-6d1c66a8ea4f.jpg)
