### ISSUE TITLE
When scrolling in mobile it re-renders once the address bar disappears

### ISSUE THREAD

**Issue by tamirgilany** [hcodes/snowflakes#58]
For example (open in mobile and see that when you scroll and the navigation bar disappears it will re-render the snowflakes)
https://tamirgilany.github.io/snowflakes_example/

![alt text](https://tamirgilany.github.io/snowflakes_example/example.gif)

**Comment by TGilany** [comment]
@hcodes think you can help with a quick fix for that?

Thanks!

**Comment by strarsis** [comment]
+1, is this a new bug? I plan to upgrade to latest `magic-snowflakes`.

**Comment by TGilany** [comment]
Hey @strarsis,
Not sure if it was fixed or not in v6.0.0 but my project was using v5.0.0

Will check tomorrow if it's fixed with the new v6.0.0 and will update.

**Comment by tamirgilany** [comment]
Hey @strarsis, seems like I'm on the latest version v6.0.1

**Comment by hcodes** [comment]
v6.1.0

Use `autoResize: false` param.
```js
new SnowFlakes({ autoResize: false });
```
